name: npm-publish

on:
  push:
    branches:
      - main
  # release:
  #   types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: login
      run: npm config set registry https://registry.npmjs.org/
      run: npm login
    
    - name: publish
      run: npm publish --access public