name: npm-publish

on: 
  push: tags

jobs:
  publish:
    runs-on: ubuntu-latest
      steps:
      - name: login
        run: npm login
      
      - name: publish
        run: npm publish --access public